# documentation: https://langfuse.com/docs
# slogan: Langfuse is an open-source LLM engineering platform that helps teams collaboratively debug, analyze, and iterate on their LLM applications.
# tags: ai, qdrant, weaviate, langchain, openai, gpt, llm, lmops, langfuse, llmops
# logo: svgs/langfuse.png
# port: 3000

version: "3"

services:
  langfuse:
    image: langfuse/langfuse:2
    restart: always
    environment:
      - DATABASE_URL=postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB:-langfuse}
      - NEXTAUTH_URL=$SERVICE_FQDN_LANGFUSE_3000
      - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
      - SALT=$SERVICE_PASSWORD_SALT
      - AUTH_DISABLE_SIGNUP=${AUTH_DISABLE_SIGNUP:-false}
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-false}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
    entrypoint:
      - node
      - web/server.js
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/api/public/health"]
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-langfuse}
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
    volumes:
      - "pg-data:/var/lib/postgresql/data"
    healthcheck:
      test:
        - CMD-SHELL
        - "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 5s
      timeout: 5s
      retries: 10
